# SPDX-FileCopyrightText: Copyright (c) 2022-2026 The Isaac Lab Project Developers.
# SPDX-License-Identifier: Apache-2.0
# Modified for dex_teleop's packaged Sharpa URDF and dex-retargeting 0.4.6.
retargeting:
  type: DexPilot
  urdf_path: overridden_at_runtime
  wrist_link_name: left_hand_C_MC
  finger_tip_link_names:
    - left_thumb_fingertip
    - left_index_fingertip
    - left_middle_fingertip
    - left_ring_fingertip
    - left_pinky_fingertip
  target_joint_names:
    - left_thumb_CMC_FE
    - left_thumb_CMC_AA
    - left_thumb_MCP_FE
    - left_thumb_MCP_AA
    - left_thumb_IP
    - left_index_MCP_FE
    - left_index_MCP_AA
    - left_index_PIP
    - left_index_DIP
    - left_middle_MCP_FE
    - left_middle_MCP_AA
    - left_middle_PIP
    - left_middle_DIP
    - left_ring_MCP_FE
    - left_ring_MCP_AA
    - left_ring_PIP
    - left_ring_DIP
    - left_pinky_CMC
    - left_pinky_MCP_FE
    - left_pinky_MCP_AA
    - left_pinky_PIP
    - left_pinky_DIP
  scaling_factor: 1.2
  low_pass_alpha: 0.2
